### ISSUE TITLE
注册提交后显示找不到页面

### ISSUE THREAD

**Issue by dingguomao** [JinkunTian/CAGarden#7]
提示信息：找不到与以下网址对应的网页：http://域名xxx/Login/Reg/registerpost.html
HTTP ERROR 404

**Comment by JinkunTian** [comment]
我在6月的时候升级了系统使用LDAP域存储账户，可能牵连到了部分注册的部分，过几天会出一个Releases解决

**Comment by JinkunTian** [comment]
改问题已在v0.0.2-pre-release中修复。
